### ISSUE TITLE
Support backends other than furaffinity.net

### ISSUE THREAD

**Issue by featherbutt** [FurryCoders/FALocalRepo#3]
### The idea

FALocalRepo is an incredible tool for downloading and locally organizing art galleries, but it's currently limited in only being able to scrape FurAffinity (or sites with identical HTML). Other gallery sites exist that have an identical or nearly identical data model, and being able to organize content from those galleries in the same local repo would useful.

I'm willing to take on the necessary work for this and submit it as a pull-request.

### Implementation ideas

The biggest obstacle is that the FA-specific code in FAAPI is closely coupled to backend-agnostic code, but this can be fixed in two ways.

1. Create a separate module for each backend site, which implements a standard interface. Allow FALocalRepo invocations to specify a module to load, with FAAPI as the default. This requires no additional changes to FAAPI, but would necessitate some amount of code duplication in each module.

2. Attempt to decouple FAAPI into its FA-specific and generic parts. The user can inject a dependency into FAAPI's constructor which overrides backend specific behavior.

Neither option would require bloating FAAPI with code for other backends. (2) seems cleaner but would require more work.

Assuming that we want to allow content from multiple backends to coexist in the same local repo, we would also need a "source" field on submissions/users/journals, both to differentiate reused IDs across backends, and as an additional field in searches.

**Comment by MatteoCampinoti94** [comment]
I like the idea!

FALocalRepo would indeed be able to handle it just by adding a source field to the tables, although I think it would be cleaner to "lock" a database to a specific site when initialize, then the user would only have to choose which database to use and the program would select the library based on the database itself.

**Comment by MatteoCampinoti94** [comment]
Alas it would require a _lot_ of work to make the necessary libraries.

Most of these sites do not have a proper API, so they'd need a scraper built for each one of them, and most of the code could not be ported over from FAAPI. The classes would probably require the least amount of work, but the parse module would have to be built from scratch with a suite of tests to ensure it keeps working.

**Comment by MatteoCampinoti94** [comment]
For example, So Furry does not have a "view all" option for the galleries, requiring branching into the sub-folders to navigate everything. It also doesn't have a previous/next button on the actual art/story pages (it has a series navigator for the latter, but it's based on the folder, not the entire gallery). Furthermore, the way user pages work (subdomains) would necessitate a rewrite of the connection module too.

**Comment by MatteoCampinoti94** [comment]
As a starting point we may want to focus on a site that has a proper API, like [Weasyl](https://projects.weasyl.com/weasylapi/).

**Comment by featherbutt** [comment]
Starting with a site that has a proper API like Weasyl makes sense.

Ironically, for SoFurry at least I already wrote a SoFurry scraper that I used to create a local backup, so converting it to a FAAPI-compatible parse module should be doable: the test suite will probably be the most laborious part.

**Comment by MatteoCampinoti94** [comment]
So, I've made a library for Weasyl :3

There are already was one called [pyweasyl](https://pypi.org/project/pyweasyl/), but it hasn't been updated in 7 years and I wanted to rewrite with proper typing and objects. It only needs a bit of testing, but otherwise it's ready and has all the API endpoints implemented with pydantic models for validation and decoding.

The problem is with FALocalRepo. I've started laying out the structure of a backend-based downloader, but it's going to require a LOT of work. The current version relies on specific functions and classes from FAAPI, so we'd have to write some generalised objects, a generalised downloader, and classes that tie the two together using the different libraries for each website.

**Comment by MatteoCampinoti94** [comment]
That's a great resource @Deer-Spangle, thanks for sharing!

Actually, feature-wise the only thing that would need adding is the ability to have multiple media files for each submission, which is something I had already considered implementing and would require only minor modifications to the database library.

I have just finished writing a generalised base class to handle download operations and it's now working fine with both FA and Weasyl. The only issue is that Weasyl has character entries, not just submissions and journals, and they have their own separate ID's. Currently I'm trying to find a way for them to coexist in the same table without resorting to multiple primary keys.

Another extra feature are SoFurry's story series, which could be generalised with grouping to support FA's folders as well, though I'm a bit reluctant to implement something so dynamic and not easily updated (if a folder changes name, then newly downloaded submissions would not be linked to older ones).

**Comment by MatteoCampinoti94** [comment]
I'm closing this issue and moving all discussions to the [Alternative FALocalRepo API Backends project](/orgs/FurryCoders/projects/1) :)

**Comment by solipsis-project** [comment]
> I'm closing this issue and moving all discussions to the [Alternative FALocalRepo API Backends project](/orgs/FurryCoders/projects/1) :)

The linked project appears to be private.

**Comment by MatteoCampinoti94** [comment]
Should be public now :)

**Comment by Deer-Spangle** [comment]
Oh, another handy resource btw: http://furbitron.com/
It has stats on how many posts per day each different furry site has, so you can see where demand might be for such projects

**Comment by solipsis-project** [comment]
I know you wanted to move discussion to the project, but it doesn't look like I can create or comment on issues there.

After talking with @featherbutt and learning what issues they ran into, I decided to try and take a stab at it myself.

I successfully refactored FAAPI in order to isolate all of the FA-specific logic to a module which implements an abstract base class. It wasn't easy, but I think I have a good foundation for making other backends.

Fork at https://github.com/solipsis-project/FAAPI

There's still some work that needs to be done:
- The current spec for the backend interface assumes that the server returns HTML/XML, which won't work with JSON APIs like Weasyl's. (Really, the best route would have been to move the parsing logic out of the data-object classes entirely and have their constructors take already-extracted data, but that seemed like a lot of labor for a proof-of-concept.)
- The interface is designed to support how SoFurry hides pooled submissions in sub-folders, but the front end of FAAPI needs some additional logic to handle this correctly.
- I tried to avoid breaking FAAPI's existing public APIs whenever possible, but there were some places where it wasn't avoidable. I need to fork the other projects that depend on FAAPI and update the affected API calls.

It won't be a full POC until I have Weasyl and SoFurry backends working, but it's a promising start that gives me confidence that other backends are possible. I also still need to document some of my design decisions.  And of course, I need to make new test cases for the other backends. I have my own test data for the FurAffinity backend, and FAAPI's test harness passes with them.

**Comment by MatteoCampinoti94** [comment]
Yeah I just noticed, I can create issues from project TODOs but there is no discussion available -.-

I think making FAAPI support both API's and HTML parsing would be too convoluted. It'd need completely separate session objects, authentication, parsers, etc.

I think the best solution is to implement backend plugins in FALocalRepo. I will create a new FALocalRepo-plugins repo with some base classes for the different plugins (backend, database, and server) so that new functionality and websites can be added more easily.

**Comment by MatteoCampinoti94** [comment]
Amazing work on the fork btw!

**Comment by MatteoCampinoti94** [comment]
I've opened discussions in the org https://github.com/orgs/FurryCoders/discussions/1 :)

**Comment by solipsis-project** [comment]
I'm getting a 404 on the discussions link; do I need to be an org member?

**Comment by MatteoCampinoti94** [comment]
It should be open now :)
